live_config_reload = true
import = [
#"~/.config/alacritty/themes/everforest_dark.toml",
#"~/.config/alacritty/themes/tokyo-night.toml",
# "~/.config/alacritty/themes/catppuccin.toml",
"~/.config/alacritty/themes/catppuccin.toml",
# "~/.config/alacritty/themes/gruvbox_material.toml",
]

[colors]
draw_bold_text_with_bright_colors = false

[font]
builtin_box_drawing = true
size = 9.0

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "W"
mods = "Alt|Shift"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Alt|Shift"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "V"
mods = "Alt|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Alt"

[[keyboard.bindings]]
action = "None"
key = "Paste"

[[keyboard.bindings]]
action = "None"
key = "Copy"

[[keyboard.bindings]]
action = "None"
key = "Insert"
mods = "Shift"

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "ExpandSelection"
mouse = "Right"

[scrolling]
history = 10000
multiplier = 20

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[shell]
program = "zsh"

[window]
decorations = "none"
decorations_theme_variant = "Dark"
dynamic_padding = false
dynamic_title = true
opacity = 1.0
resize_increments = false
startup_mode = "Windowed"
title = "Alacritty"

[window.dimensions]
columns = 140
lines = 35

[window.padding]
x = 10
y = 10

[window.position]
x = 180
y = 90
