gaps:
  inner_gap: 2
  outer_gap: 2

general:
  show_floating_on_top: false
  toggle_workspace_on_refocus: false
  # focus_border_color: "#ffffff33"

bar:
  height: "30px"
  position: "top"
  always_on_top: true
  opacity: 1.0
  
  background: "#696969"
  # foreground: "#000000"
  foreground: "#ffffff"
  font_family: "Segoe UI"
  font_size: "13px"
  padding: "4px 6px"
  offset_x: "0"
  offset_y: "0"
  border_radius: "0"

  components_left:
    - type: "workspaces"
      focused_workspace_background: "#778899"
      displayed_workspace_background: "#A9A9A9"
      default_workspace_background: "transparent"
  components_center:
    - type: "window title"
      background: "#FFF0F5"
      foreground: "#000000"
      padding: "0 8px"
  components_right:
    - type: "tiling direction"
      label_horizontal: "⮂"
      label_vertical: "⮁"
      background: "#4682B4"
      margin: "0 4px"
      padding: "0 8px"

    - type: "binding mode"
      background: "#4682B4"
      margin: "0 4px 0 0"
      padding: "0 8px"

    - type: "clock"
      time_formatting: "hh:mm tt"
      background: "#F5DEB3"
      foreground: "#000000"
      margin: "0 8px 0 8px"
      padding: "0 8px"

    - type: "battery"
      label_draining: "[{battery_level}%]"
      label_power_saver: "[{battery_level}%]"
      label_charging: "[{battery_level}%]"
      foreground: "#2E8B57"
      background: "#FFF5EE"
      margin: "0 4px"
      padding: "0 8px"

workspaces:
  - name: "1"
    display_name: "Violet"
  - name: "2"
    display_name: "Ayanami"
  - name: "3"
    display_name: "Ishimiya"
  - name: "4"
    display_name: "Mikasa"
  - name: "5"
    display_name: "Alen"
  - name: "6"
  - name: "7"
  - name: "8"
  - name: "9"

window_rules:
  - command: "ignore"
    match_process_name: "Taskmgr"

  - command: "set floating"
    match_class_name: "#32770"

  - command: "resize borders 0px -7px -7px -7px"
    match_process_name: "steam"

binding_modes:
  - name: "resize"
    keybindings:
      - command: "resize width -2%"
        bindings: ["H", "Left"]
      - command: "resize width +2%"
        bindings: ["L", "Right"]
      - command: "resize height +2%"
        bindings: ["K", "Up"]
      - command: "resize height -2%"
        bindings: ["J", "Down"]
      - command: "binding mode none"
        bindings: ["Escape", "Enter"]

keybindings:
  - command: "focus left"
    bindings: ["Alt+H", "Alt+Left"]
  - command: "focus right"
    bindings: ["Alt+L", "Alt+Right"]
  - command: "focus up"
    bindings: ["Alt+K", "Alt+Up"]
  - command: "focus down"
    bindings: ["Alt+J", "Alt+Down"]

  - command: "move left"
    bindings: ["Alt+Shift+H", "Alt+Shift+Left"]
  - command: "move right"
    bindings: ["Alt+Shift+L", "Alt+Shift+Right"]
  - command: "move up"
    bindings: ["Alt+Shift+K", "Alt+Shift+Up"]
  - command: "move down"
    bindings: ["Alt+Shift+J", "Alt+Shift+Down"]

  - command: "resize width -2%"
    binding: "Alt+U"
  - command: "resize width +2%"
    binding: "Alt+P"
  - command: "resize height +2%"
    binding: "Alt+O"
  - command: "resize height -2%"
    binding: "Alt+I"

  - command: "binding mode resize"
    binding: "Alt+R"

  - command: "tiling direction toggle"
    binding: "Alt+V"

  - command: "focus mode toggle"
    binding: "Alt+T"

  - command: "toggle floating"
    binding: "Alt+F"

  - command: "toggle maximized"
    binding: "Alt+X"

  - command: "set minimized"
    binding: "Alt+M"

  - command: "close"
    binding: "Alt+Shift+Q"

  - command: "exit wm"
    binding: "Alt+Shift+E"

  - command: "reload config"
    binding: "Alt+Shift+R"

  - command: "exec wt"
    binding: "Shift+Enter"

  - command: "focus workspace recent"
    binding: "Alt+Y"

  - command: "focus workspace 1"
    binding: "Alt+1"
  - command: "focus workspace 2"
    binding: "Alt+2"
  - command: "focus workspace 3"
    binding: "Alt+3"
  - command: "focus workspace 4"
    binding: "Alt+4"
  - command: "focus workspace 5"
    binding: "Alt+5"
  - command: "focus workspace 6"
    binding: "Alt+6"
  - command: "focus workspace 7"
    binding: "Alt+7"
  - command: "focus workspace 8"
    binding: "Alt+8"
  - command: "focus workspace 9"
    binding: "Alt+9"

  - commands: ["move to workspace 1", "focus workspace 1"]
    binding: "Alt+Shift+1"
  - commands: ["move to workspace 2", "focus workspace 2"]
    binding: "Alt+Shift+2"
  - commands: ["move to workspace 3", "focus workspace 3"]
    binding: "Alt+Shift+3"
  - commands: ["move to workspace 4", "focus workspace 4"]
    binding: "Alt+Shift+4"
  - commands: ["move to workspace 5", "focus workspace 5"]
    binding: "Alt+Shift+5"
  - commands: ["move to workspace 6", "focus workspace 6"]
    binding: "Alt+Shift+6"
  - commands: ["move to workspace 7", "focus workspace 7"]
    binding: "Alt+Shift+7"
  - commands: ["move to workspace 8", "focus workspace 8"]
    binding: "Alt+Shift+8"
  - commands: ["move to workspace 9", "focus workspace 9"]
    bindings: ["Alt+Shift+9"]
